# Generated by Django 3.1.1 on 2020-10-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rope', '0002_auto_20201003_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buffalo',
        ),
    ]
